- name: Name of task
  debug:
    msg: "SETTING UP SECRET FILES"
  tags: &tags_for_secret_files ["secret-files", "bs"]

- name: Create secret directories
  loop: [".ssh", ".secrets", ".auth_codes"]
  file:
    dest: "{{ HOME }}/{{ item }}"
    mode: 0700
    state: directory
  tags: *tags_for_secret_files

- name: Copy secret files
  loop: [".ssh", ".secrets", ".auth_codes"]
  copy:
    src: files/{{ item }}/
    dest: "{{ HOME }}/{{ item }}"
    mode: 0400
  tags: *tags_for_secret_files
