# install i3...
- name: Name of task
  debug:
    msg: "SETTING UP GUI"
  tags: &tags_for_gui ["gui", "bs"]

- name: Install GUI
  become: true
  loop:
    - dmenu
    - pulseaudio
    - pavucontrol
    - terminator
    - vlc
    - network-manager-openvpn-gnome
    - network-manager-gnome
    - brave-browser
    - code
    - light
    - yubikey-manager #https://gist.github.com/artizirk/d09ce3570021b0f65469cb450bee5e29
    - sway
    - swaybg
    - swayidle
    - swayimg
    - swaylock
    - fonts-font-awesome
    - acpi
    - bc
    - wdisplays
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  tags: *tags_for_gui
#nvim, slack, telegram, toolbox, obsidian, sync, toolbox, kwm
