# install i3...
- name: Name of task
  debug:
    msg: "SETTING UP GUI"
  tags: &tags_for_gui ["gui", "bs"]

- name: Install GUI
  become: true
  loop:
    - i3
    - i3lock
    - i3status
    - dmenu
    - xorg
    - lightdm
    #- slick-greeter
    #- lightdm-settings
    #- lxappearance
    #- nitrogen BG
    - pulseaudio
    - pavucontrol
    #- pipewire-audio
    #- alsa-utils
    - terminator
    - thunar # file manager
    - evince # pdf viewer
    - vlc
    - network-manager-openvpn-gnome
    - network-manager-gnome
    - brave-browser
    - code
    - x11-xserver-utils
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
  tags: *tags_for_gui
